app = 'furi'
primary_region = 'iad'

[[mounts]]
source = 'data'
destination = '/data'
initial_size = '5gb'

[http_service]
internal_port = 9339
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
